version: '3.8'

services:
  dimibot:
    build: .
    container_name: dimibot
    restart: unless-stopped
    ports:
      - "8443:8443"
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - WEBHOOK_URL=${WEBHOOK_URL:-https://dimibot.coolphill.com/webhook}
      - PORT=8443
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8443/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dimibot.rule=Host(`dimibot.coolphill.com`)"
      - "traefik.http.routers.dimibot.tls=true"
      - "traefik.http.routers.dimibot.tls.certresolver=letsencrypt"
      - "traefik.http.services.dimibot.loadbalancer.server.port=8443"